config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'privacy', to: 'static_pages#privacy'
  get 'service', to: 'static_pages#service'
  resources :users, only: %i[new create destroy]
  resource :profile, only: %i[show edit update]
  resources :study_times, only: %i[new create index update destroy] do
    member do
      patch :finish
      get :edit_timestamps
      patch :change_timestamps
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/study_time.rb
class StudyTime < ApplicationRecord
  belongs_to :user, class_name: 'User'

  validates :user_id, presence: true
  validates :status, uniqueness: { scope: :user_id}, if: -> { status == 0 }
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  mount_uploader :avatar, AvatarUploader
  has_many :study_times, dependent: :destroy

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :name, presence: true, length: { maximum: 255 }

  validates :email, uniqueness: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  before_action :require_login

  private

  def not_authenticated
    flash[:warning] = t('defaults.message.require_login')
    redirect_to login_path
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: %i[edit update]

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to profile_path, success: t('defaults.message.updated', item: User.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: User.model_name.human)
      render :edit
    end
  end

  def show
    @study_time = StudyTime.where(user_id: current_user.id, status: 1).order(created_at: :desc)
    @total_time = StudyTime.where(user_id: current_user.id).sum(:total_time)
    @study_time = StudyTime.where(user_id: current_user.id, status: 1).order(created_at: :desc).page(params[:page])
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:email, :name, :avatar, :avatar_cache, :role)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login
  def top; end

  def privacy; end

  def service; end
end

app/controllers/study_times_controller.rb
class StudyTimesController < ApplicationController
  skip_before_action :require_login, only: %i[index]

  def new
    if current_user.study_times.exists?(status: 0)
      redirect_to study_times_path, alert: t('defaults.message.already_have_study_time')
    else
      @study_time = StudyTime.new
    end
  end

  def create
    @study_time = current_user.study_times.build
    @study_time.save
    redirect_to study_times_path
  end

  def index
    @study_time = StudyTime.where(status: 0).order(created_at: :desc)
  end

  def update
    @study_time = StudyTime.find(params[:id])
    elapsed_time = (Time.now - @study_time.created_at) / 60
    @study_time.total_time = elapsed_time.to_i
    @study_time.touch(:updated_at)
    @study_time.save
    redirect_to study_times_path
  end

  def finish
    @study_time = StudyTime.find(params[:id])
    elapsed_time = (Time.now - @study_time.created_at) / 60
    @study_time.total_time = elapsed_time.to_i
    @study_time.touch(:updated_at)
    @study_time.status = 1
    @study_time.save
    redirect_to profile_path
  end

  def destroy
    @study_time = StudyTime.find(params[:id])
    @study_time.destroy
    redirect_to profile_path
  end

  def edit_timestamps
    @study_time = StudyTime.find(params[:id])
  end

  def change_timestamps
    @study_time = StudyTime.find(params[:id])
    created_at = Time.zone.local(*params[:study_time].values_at('created_at(1i)', 'created_at(2i)', 'created_at(3i)', 'created_at(4i)', 'created_at(5i)'))
    updated_at = Time.zone.local(*params[:study_time].values_at('updated_at(1i)', 'updated_at(2i)', 'updated_at(3i)', 'updated_at(4i)', 'updated_at(5i)'))
    @study_time.created_at = created_at
    @study_time.updated_at = updated_at
    @study_time.total_time = ((updated_at - created_at) / 60).to_i
    if @study_time.save(validate: false)
      redirect_to profile_path, notice: t("defaults.message.updated")
    else
      render :edit_timestamps
    end
  end

  private

  def study_time_params
    params.require(:study_time)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to study_times_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def destroy
    logout
    redirect_to login_path, success: t('.success'), status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to study_times_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'ユーザーを削除しました。'
    redirect_to :root
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/users_sessions_helper.rb
module UsersSessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="cupcake" class= "font-top  text-maincolor">
<link href="https://fonts.googleapis.com/css2?family=Emblema+One&family=Kosugi+Maru&display=swap" rel="stylesheet">
<script src="https://kit.fontawesome.com/95ae21fd7d.js" crossorigin="anonymous"></script>
  <head>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-JLLP5YDYPQ"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-JLLP5YDYPQ');
    </script>
    <%= favicon_link_tag('favicon.ico') %>
    <title>StudyingTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application.tailwind', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag "application.tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <% if logged_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
<html>

app/views/profiles/edit.html.erb
<div class="flex justify-center text-center my-12">
  <div class="">
    <div class="">
      <h1 class="text-3xl my-5"><%= t('.title') %></h1>
    </div>
    <%= form_with model: @user, url: profile_path, local: true do |f| %>
      <%== render 'shared/error_messages', object: f.object %>
      <div class="mb-3">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'w-full m-3 p-3' %>
      </div>

      <div class="mb-3">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'w-full m-3 p-3' %>
      </div>

      <div class="mb-3">
        <%= f.label :avatar %>
        <%= f.file_field :avatar, onchange: 'previewFileWithId(preview)', class: 'form-control mb-3', accept: 'image/*' %>
        <%= f.hidden_field :avatar_cache %>
      </div>

      <div class="d-grid">
        <%= f.submit class: 'btn btn-primary text-headfoot' %>
      </div>
    <% end %>
  </div>
</div>

app/views/profiles/show.html.erb
<% content_for(:title, t('.title')) %>
<div class="container px-5 py-20 mx-auto">
  <div class="col-md-10 offset-md-1">
    <div class="flex flex-col text-center w-full mb-5">
      <div class="text-3xl mb-4"><%= t('.title') %></div>
    </div>
    <%= link_to t('defaults.edit'), edit_profile_path, class: 'btn btn-success float-right text-headfoot' %>
    <table class="table">
      <tr>
        <th scope="row"><%= t(User.human_attribute_name(:email)) %></th>
        <td><%= current_user.email %></td>
      </tr>
      <tr>
        <th scope="row"><%= t(User.human_attribute_name(:name)) %></th>
        <td><%= current_user.name %></td>
      </tr>
      <tr>
        <th scope="row"><%= t(User.human_attribute_name(:avatar)) %></th>
        <td>
          <div class="avatar">
            <div class="w-16 rounded-full">
              <%= image_tag current_user.avatar.url %>
            </div>
          </div>
        </td>
      </tr>
      <tr>
        <th class= "text-xl",scope="row"><%= t('.total_time') %>  <%="#{@total_time / 60}"%><%=t('.hour')%><%="#{@total_time % 60}"%><%=t('.minute') %></th>
      </tr>
    </table>
    <br>
    <br>
    <div class="flex flex-col text-center w-full mb-20">
      <% if @study_time.present? %>
        <div class="text-3xl mb-4"><%= t('.study_times') %></div>
          <div class="flex flex-wrap -m-2">
            <%= render @study_time %>
          </div>
        </div>
      <% else %>
        <div class="flex flex-col text-center w-full mb-20">
          <div class="text-3xl mb-4"><%= t('.no_result') %></div>
        </div>
      <% end %>
    </div>
    <div class="flex justify-center text-center text-2xl">
      <%= paginate @study_time %>
    </div>
    <%= button_to t('users.destroy'), user_path(current_user.id), class: 'btn btn-secondary float-right text-headfoot', method: :delete, "data-confirm" => t('defaults.message.destroy_confirm') %>
    <br>
    <br>
  </div>
</div>

app/views/shared/_before_login_header.html.erb
<header data-theme="retro", class= "py-20">
  <div class="container mx-auto flex flex-wrap flex-col md:flex-row items-center">
    <div class="font-title">
      <%= link_to "Studying Tracker", root_path, class: "text-5xl text-headfoot" %>
    </div>
    <div class="md:ml-auto flex flex-wrap items-center text-base md:text-xl justify-center">
      <%= link_to (t 'study_times.index.title'), study_times_path, class: "btn mr-5 text-headfoot"%>
      <%= link_to (t 'defaults.loginpage'), login_path, class: "btn mr-5 text-headfoot"%>
      <%= link_to (t 'defaults.register_page'), new_user_path, class: "btn mr-5 text-headfoot"%>
    </div>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> text-headfoot"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer data-theme="retro", class="p-20 text-xl">
  <div class="flex-wrap justify-center text-headfoot">
    <p>Developed by team satoharu</p>
    <p>44期:おおくまりょうや 44期:おのたつや 44期:さとうはるか 44期:やましたたかひろ</p>
    <br>
    <p>Special Thanks.</p>
    <p>34期:れなっちさん 36期:ふじいさん 39期:yutaさん 40期:ミツさん</p>
    <br>
    <%= link_to (t 'policy.privacy_policy'), privacy_path, class: "btn mr-5 text-headfoot"%>
    <%= link_to (t 'policy.terms_of_service'), service_path, class: "btn mr-5 text-headfoot"%>
  </div>
</footer>

app/views/shared/_header.html.erb
<header data-theme="retro", class= "py-20">
  <div class="container mx-auto flex flex-wrap flex-col md:flex-row items-center">
    <div class="font-title">
      <%= link_to "Studying Tracker", root_path, class: "text-5xl text-headfoot" %>
    </div>
    <div class="md:ml-auto flex flex-wrap items-center text-base md:text-xl justify-center">
      <% unless current_user.study_times.exists?(status: 0) %>
        <%= link_to (t 'study_times.new.title'), new_study_time_path, class: "btn mr-5 text-headfoot"%>
      <% end %>
      <%= link_to (t 'study_times.index.title'), study_times_path, class: "btn mr-5 text-headfoot"%>
      <%= link_to (t "profiles.show.title"), profile_path, class: "btn mr-5 text-headfoot" %>
      <%= button_to (t 'defaults.logout'), logout_path, method: :delete, class: "btn mr-5 text-headfoot" %>
      <div class="avatar">
        <div class="w-16 rounded-full">
          <%= image_tag current_user.avatar.url %>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/static_pages/privacy.html.erb
<br>
<br>
<br>
<p class="text-2xl text-center" text-align: center;>プライバシーポリシー</p>
<br>
<br>
<table class="table table-pin-rows text-1xl">
  <tbody>
    <tr></tr>
    <tr><td>team satoharu（以下，「当チーム」といいます。）は，本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。</td></tr>
    <tr><td>第1条（個人情報）<br>
    「個人情報」とは，個人情報保護法にいう「個人情報」を指すものとし，生存する個人に関する情報であって，当該情報に含まれる氏名，生年月日，住所，電話番号，連絡先その他の記述等により特定の個人を識別できる情報及び容貌，指紋，声紋にかかるデータ，及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。</td></tr>
    <tr><td>第2条（個人情報の収集方法）<br>
    当チームは，ユーザーが利用登録をする際にニックネーム，メールアドレスなどの個人情報をお尋ねすることがあります。</td></tr>
    <tr><td>第3条（個人情報を収集・利用する目的）<br>
    当チームが個人情報を収集・利用する目的は，以下のとおりです。<br>
      ・当チームサービスの提供・運営のため<br>
      ・ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）<br>
      ・利用規約に違反したユーザーや，不正・不当な目的でサービスを利用しようとするユーザーの特定をし，ご利用をお断りするため<br>
      ・ユーザーにご自身の登録情報の閲覧や変更，削除，ご利用状況の閲覧を行っていただくため<br>
      ・上記の利用目的に付随する目的</td></tr>
    <tr><td>第4条（利用目的の変更）<br>
    当チームは，利用目的が変更前と関連性を有すると合理的に認められる場合に限り，個人情報の利用目的を変更するものとします。<br>
    利用目的の変更を行った場合には，変更後の目的について，当チーム所定の方法により，ユーザーに通知し，または本ウェブサイト上に公表するものとします。</td></tr>
    <tr><td>第5条（個人情報の第三者提供）<br>
    当チームは，次に掲げる場合を除いて，あらかじめユーザーの同意を得ることなく，第三者に個人情報を提供することはありません。ただし，個人情報保護法その他の法令で認められる場合を除きます。<br>
      ・人の生命，身体または財産の保護のために必要がある場合であって，本人の同意を得ることが困難であるとき<br>
      ・公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき<br>
      ・国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき<br>
      ・予め次の事項を告知あるいは公表し，かつ当チームが個人情報保護委員会に届出をしたとき<br>
        &emsp;⚫︎利用目的に第三者への提供を含むこと<br>
        &emsp;⚫︎第三者に提供されるデータの項目<br>
        &emsp;⚫︎第三者への提供の手段または方法<br>
        &emsp;⚫︎本人の求めに応じて個人情報の第三者への提供を停止すること<br>
        &emsp;⚫︎本人の求めを受け付ける方法<br>
    <br>
    前項の定めにかかわらず，次に掲げる場合には，当該情報の提供先は第三者に該当しないものとします。<br>
      ・当チームが利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合<br>
      ・合併その他の事由による事業の承継に伴って個人情報が提供される場合<br>
      ・個人情報を特定の者との間で共同して利用する場合であって，その旨並びに共同して利用される個人情報の項目，共同して利用する者の範囲，利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について，あらかじめ本人に通知し，または本人が容易に知り得る状態に置いた場合</td></tr>
    <tr><td>第6条（個人情報の開示）<br>
    当チームは，本人から個人情報の開示を求められたときは，本人に対し，遅滞なくこれを開示します。ただし，開示することにより次のいずれかに該当する場合は，その全部または一部を開示しないこともあり，開示しない決定をした場合には，その旨を遅滞なく通知します。<br>
      ・本人または第三者の生命，身体，財産その他の権利利益を害するおそれがある場合<br>
      ・当チームの業務の適正な実施に著しい支障を及ぼすおそれがある場合<br>
      ・その他法令に違反することとなる場合<br>
    <br>
    前項の定めにかかわらず，履歴情報および特性情報などの個人情報以外の情報については，原則として開示いたしません。</td></tr>
    <tr><td>第7条（個人情報の訂正および削除）<br>
    ・ユーザーは，当チームの保有する自己の個人情報が誤った情報である場合には，当チームが定める手続きにより，当チームに対して個人情報の訂正，追加または削除（以下，「訂正等」といいます。）を請求することができます。<br>
    ・当チームは，ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の訂正等を行うものとします。<br>
    ・当チームは，前項の規定に基づき訂正等を行った場合，または訂正等を行わない旨の決定をしたときは遅滞なく，これをユーザーに通知します。</td></tr>
    <tr><td>第8条（個人情報の利用停止等）<br>
    ・当チームは，本人から，個人情報が，利用目的の範囲を超えて取り扱われているという理由，または不正の手段により取得されたものであるという理由により，その利用の停止または消去（以下，「利用停止等」といいます。）を求められた場合には，遅滞なく必要な調査を行います。<br>
    ・前項の調査結果に基づき，その請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の利用停止等を行います。<br>
    ・当チームは，前項の規定に基づき利用停止等を行った場合，または利用停止等を行わない旨の決定をしたときは，遅滞なく，これをユーザーに通知します。<br>
    ・前2項にかかわらず，利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって，ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は，この代替策を講じるものとします。</td></tr>
    <tr><td>第9条（プライバシーポリシーの変更）<br>
    ・本ポリシーの内容は，法令その他本ポリシーに別段の定めのある事項を除いて，ユーザーに通知することなく，変更することができるものとします。<br>
    ・当チームが別途定める場合を除いて，変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。</td></tr>
    <tr><td>第10条（お問い合わせ窓口）<br>
    本ポリシーに関するお問い合わせは，下記の窓口までお願いいたします。<br>
    Twitter ID：@Rz0Bp</td></tr>
    <tr><td>以上</td></tr>
    <tr></tr>
  </tbody>
</table>
<br>
<br>
<br>

app/views/study_times/_study_time.html.erb
<div class="p-1 lg:w-1/3 md:w-1/2 w-full">
  <div class="h-full flex items-center border-accent-content border p-4 rounded-lg ">
    <div class="avatar">
      <div class="w-16 h-16 object-cover object-center flex-shrink-0 rounded-full mr-4">
        <%= image_tag study_time.user.avatar.url %>
      </div>
    </div>
    <div class="flex-grow text-lg">
      <%= study_time.user.name %>
      <p><%= t(StudyTime.human_attribute_name(:created_at)) %> <%= l study_time.created_at, format: :long %></p>
      <% if study_time.status == 0 %>
        <p><%= t(StudyTime.human_attribute_name(:updated_at)) %> <%= l study_time.updated_at, format: :long %></p>
      <% else %>
        <p><%= t('study_times.end_time') %> <%= l study_time.updated_at, format: :long %></p>
      <% end %>
      <p><%= t(StudyTime.human_attribute_name(:total_time)) %> <%= "#{study_time.total_time / 60}時間#{study_time.total_time % 60}分" %></p>
      <div class="flex items-center flex-wrap justify-end">
        <% if current_user &&(current_user == study_time.user && study_time.status == 0) || current_user &&(current_user.role == 1 && study_time.status == 0) %>
          <%= link_to t('study_times.tweet'), "https://twitter.com/share?url=https://studying-tracker.fly.dev/&text=#{study_time.user.name}さんの現在の学習時間は#{study_time.total_time / 60}時間#{study_time.total_time % 60}分です！%0A&hashtags=StudyingTracker", class: 'btn btn-info fa-brands fa-twitter fa-2xl text-twitter', target: '_blank' %>
          <%= form_with(model: study_time, url: study_time_path(study_time)) do |f| %>
            <%= f.submit t('study_times.update'), class: "btn btn-primary text-headfoot" %>
          <% end %>
          <%= form_with(model: study_time, url: finish_study_time_path(study_time)) do |f| %>
            <%= f.submit t('study_times.end'), class: "btn btn-secondary text-headfoot" %>
          <% end %>
        <% end %>
        <% if current_user == study_time.user && study_time.status == 1 %>
          <%= link_to t('study_times.tweet'), "https://twitter.com/share?url=https://studying-tracker.fly.dev/&text=#{study_time.user.name}さんの今回の学習時間は#{study_time.total_time / 60}時間#{study_time.total_time % 60}分でした！%0A&hashtags=StudyingTracker", class: 'btn btn-info fa-brands fa-twitter fa-2xl text-twitter', target: '_blank' %>
          <%= link_to  t('study_times.edit.edit_study_times'), edit_timestamps_study_time_path(study_time), class: "btn btn-primary text-headfoot" %>
          <%= button_to t('study_times.destroy'), study_time_path(study_time), class: "btn btn-secondary text-headfoot", method: :delete, "data-confirm" => t('defaults.message.destroy_confirm') %>
        <% end %>
        </div>
    </div>
  </div>
</div>

app/views/study_times/edit_timestamps.html.erb
<div class="flex justify-center text-center my-12">
  <div class="">
    <div class="">
      <h1 class="text-3xl my-10"><%= t('.title') %></h1>
    </div>
    <%= form_with(model: @study_time, url: change_timestamps_study_time_path(@study_time), local: true) do |f| %>
      <%== render 'shared/error_messages', object: f.object %>
      <div class="mb-10 field">
        <%= f.label :created_at, class: 'text-2xl' %>
        <%= f.datetime_select :created_at, class: 'w-full' %>
      </div>
      <div class="mb-10 field">
        <%= f.label :updated_at, class: 'text-2xl' %>
        <%= f.datetime_select :updated_at, class: 'w-full' %>
      </div>
      <div class="d-grid">
        <%= f.submit class: 'btn btn-primary text-headfoot' %>
        <%= link_to t('study_times.edit.back'), profile_path, class: 'btn btn-primary text-headfoot' %>
      </div>
    <% end %>
  </div>
</div>

app/views/user_sessions/new.html.erb
<div class="flex justify-center text-center my-12">
  <div class="">
    <div class="">
      <h1 class="text-3xl my-5"><%= t('.title') %></h1>
    </div>
    <%= form_with model: @user, local: true do |f| %>
      <div class="mb-3">
        <%= f.label :email, User.human_attribute_name(:email) %>
        <%= f.email_field :email, class: 'w-full m-3 p-3' %>
      </div>
      <div class="mb-3">
        <%= f.label :password, User.human_attribute_name(:password) %>
        <%= f.password_field :password, class: 'w-full m-3 p-3' %>
      </div>
      <div class="actions">
        <%= f.submit (t 'defaults.login'), class: 'btn btn-primary text-headfoot' %>
      </div><br><br>
      <div class='text-center'>
        <%= link_to (t '.to_register_page'), new_user_path, class: 'btn btn-primary text-headfoot' %>
      </div>
    <% end %>
  </div>
</div>